spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/register_manager
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      #ddl-auto: none
    properties:
      hibernate.format_sql: true

server:
  port: 8081

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  file:
    name: register-manager.log
  level:
    root: warn
#Trace, debug, info, warn, error

app:
  session:
    expirationtime: 30


viacep:
  url:  https://viacep.com.br/ws/